# Generated by Django 2.1.7 on 2021-12-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnishing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnishing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
