# Generated by Django 2.1.7 on 2021-12-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='firm_name',
            field=models.CharField(blank=True, default='Vida Properties', max_length=100),
        ),
    ]
