# Generated by Django 2.1.7 on 2021-12-16 15:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import house.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('furnishing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('sqft', models.IntegerField(blank=True, null=True)),
                ('lot_size', models.IntegerField(blank=True, null=True)),
                ('garage', models.IntegerField(blank=True, null=True)),
                ('pool', models.BooleanField(default=False)),
                ('boys_quarters', models.BooleanField(default=False)),
                ('self_compound', models.BooleanField(default=False)),
                ('build_condition', models.CharField(help_text='Newly Built or Renovated', max_length=20)),
                ('facilities', models.TextField(blank=True, help_text='Facilities in the apartment')),
                ('date_listed', models.DateTimeField(default=datetime.datetime.now)),
                ('agency_fee', models.BooleanField(default=True)),
                ('main_image', models.ImageField(upload_to='main_image/&Y/&m/&d/')),
                ('video_of', models.FileField(blank=True, null=True, upload_to='videos/&Y/&m/&d/', validators=[house.validators.validate_video_extension], verbose_name='Video of Building')),
                ('image_1', models.ImageField(blank=True, upload_to='image_1/&Y/&m/&d/')),
                ('image_2', models.ImageField(blank=True, upload_to='image_2/&Y/&m/&d/')),
                ('image_3', models.ImageField(blank=True, upload_to='image_3/&Y/&m/&d/')),
                ('image_4', models.ImageField(blank=True, upload_to='image_4/&Y/&m/&d/')),
                ('image_5', models.ImageField(blank=True, upload_to='image_5/&Y/&m/&d/')),
                ('image_6', models.ImageField(blank=True, upload_to='image_6/&Y/&m/&d/')),
                ('image_7', models.ImageField(blank=True, upload_to='image_7/&Y/&m/&d/')),
                ('image_8', models.ImageField(blank=True, upload_to='image_8/&Y/&m/&d/')),
                ('image_9', models.ImageField(blank=True, upload_to='image_9/&Y/&m/&d/')),
                ('image_10', models.ImageField(blank=True, upload_to='image_10/&Y/&m/&d/')),
                ('published', models.BooleanField(default=False)),
                ('slug', models.SlugField(default='', help_text='Enter any text', unique=True)),
                ('furnished', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='furnishing.Furnishing')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtor.Realtor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
