# Generated by Django 2.1.7 on 2021-12-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_10',
            field=models.ImageField(blank=True, upload_to='image_10/&Y/&m/&d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_7',
            field=models.ImageField(blank=True, upload_to='image_7/&Y/&m/&d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_8',
            field=models.ImageField(blank=True, upload_to='image_8/&Y/&m/&d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_9',
            field=models.ImageField(blank=True, upload_to='image_9/&Y/&m/&d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='video_of',
            field=models.FileField(null=True, upload_to='videos/&Y/&m/&d/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='image_1/&Y/&m/&d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='image_2/&Y/&m/&d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='image_3/&Y/&m/&d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='image_4/&Y/&m/&d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_5',
            field=models.ImageField(blank=True, upload_to='image_5/&Y/&m/&d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_6',
            field=models.ImageField(blank=True, upload_to='image_6/&Y/&m/&d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sqft',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
