# Generated by Django 2.1.7 on 2021-12-09 14:28

from django.db import migrations, models
import house.validators


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20211209_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='video_of',
            field=models.FileField(blank=True, null=True, upload_to='videos/&Y/&m/&d/', validators=[house.validators.validate_video_extension], verbose_name='Video of Building'),
        ),
    ]
